<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family: sans-serif; background: #f5f5f5; padding: 20px;">
<div style="max-width: 600px; margin: auto; background: white; border-radius: 8px; padding: 30px;">
    <h1 style="color: #d97706; margin: 0 0 5px;">{{ $callSheet->film->title }}</h1>
    <p style="color: #666; font-size: 14px;">Call Sheet for <strong>{{ $callSheet->shoot_date }}</strong></p>
    <hr style="border: none; border-top: 1px solid #eee; margin: 20px 0;">
    <p style="color: #333; font-size: 14px; line-height: 1.6;">Please find the attached call sheet for <strong>{{ $callSheet->shoot_date }}</strong>.</p>
    <table style="width: 100%; border-collapse: collapse; margin: 15px 0;">
        <tr><td style="padding: 8px; color: #666; font-size: 13px;">Call Time</td><td style="padding: 8px; font-size: 13px; font-weight: bold;">{{ $callSheet->general_call_time }}</td></tr>
        <tr><td style="padding: 8px; color: #666; font-size: 13px;">Location</td><td style="padding: 8px; font-size: 13px; font-weight: bold;">{{ $callSheet->location?->name ?? '—' }}</td></tr>
        <tr><td style="padding: 8px; color: #666; font-size: 13px;">Crew on Call</td><td style="padding: 8px; font-size: 13px; font-weight: bold;">{{ $callSheet->entries->count() }} members</td></tr>
    </table>
    <hr style="border: none; border-top: 1px solid #eee; margin: 20px 0;">
    <p style="color: #999; font-size: 12px;">Generated by Nepal Film OS</p>
</div>
</body>
</html>
